version: "3.9"
services:
  rabbitMq:
    container_name: backupR_rabbitMq
    image: masstransit/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
      
  webapi:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - 5237:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development